# Form implementation generated from reading ui file 'coffeelion.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_coffeelion(object):
    def setupUi(self, coffeelion):
        coffeelion.setObjectName("coffeelion")
        coffeelion.resize(843, 903)
        self.centralwidget = QtWidgets.QWidget(parent=coffeelion)
        self.centralwidget.setObjectName("centralwidget")
        self.dynamicBtn = QtWidgets.QWidget(parent=self.centralwidget)
        self.dynamicBtn.setGeometry(QtCore.QRect(500, 30, 321, 821))
        self.dynamicBtn.setObjectName("dynamicBtn")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(30, 30, 461, 821))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.order_table = QtWidgets.QTableWidget(parent=self.widget)
        self.order_table.setObjectName("order_table")
        self.order_table.setColumnCount(0)
        self.order_table.setRowCount(0)
        self.verticalLayout.addWidget(self.order_table)
        self.l1_totalprice = QtWidgets.QLabel(parent=self.widget)
        self.l1_totalprice.setObjectName("l1_totalprice")
        self.verticalLayout.addWidget(self.l1_totalprice, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.order_pushButton = QtWidgets.QPushButton(parent=self.widget)
        self.order_pushButton.setObjectName("order_pushButton")
        self.horizontalLayout.addWidget(self.order_pushButton)
        self.checkout_pushButton = QtWidgets.QPushButton(parent=self.widget)
        self.checkout_pushButton.setObjectName("checkout_pushButton")
        self.horizontalLayout.addWidget(self.checkout_pushButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.log_textBrowser = QtWidgets.QTextBrowser(parent=self.widget)
        self.log_textBrowser.setObjectName("log_textBrowser")
        self.verticalLayout.addWidget(self.log_textBrowser)
        self.order_table.raise_()
        self.checkout_pushButton.raise_()
        self.log_textBrowser.raise_()
        self.log_textBrowser.raise_()
        self.order_pushButton.raise_()
        self.dynamicBtn.raise_()
        coffeelion.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=coffeelion)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 843, 21))
        self.menubar.setObjectName("menubar")
        coffeelion.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=coffeelion)
        self.statusbar.setObjectName("statusbar")
        coffeelion.setStatusBar(self.statusbar)

        self.retranslateUi(coffeelion)
        QtCore.QMetaObject.connectSlotsByName(coffeelion)

    def retranslateUi(self, coffeelion):
        _translate = QtCore.QCoreApplication.translate
        coffeelion.setWindowTitle(_translate("coffeelion", "MainWindow"))
        self.l1_totalprice.setText(_translate("coffeelion", "總價: 0 元"))
        self.order_pushButton.setText(_translate("coffeelion", "Order"))
        self.checkout_pushButton.setText(_translate("coffeelion", "Checkout"))
